version: '3'

services:
  proxy-server:
    build: 
      context: ./proxy-server
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - target-server

  target-server:
    build: 
      context: ./target-server
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
